### ISSUE TITLE
Circle-CI build failing due to ModuleNotFoundError on hydra

### ISSUE THREAD

**Issue by alvarobartt** [pytorch/hub#156]
As spotted while creating the PR #155, the Circle-CI build is failing with the following error code while trying to load the `RoBERTa-Large` model from `pytorch/fairseq`:

```
Traceback (most recent call last):
  File "temp.py", line 2, in <module>
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
  File "/home/circleci/miniconda3/lib/python3.7/site-packages/torch/hub.py", line 349, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/circleci/miniconda3/lib/python3.7/site-packages/torch/hub.py", line 71, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/circleci/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 8, in <module>
    from fairseq.hub_utils import BPEHubInterface as bpe  # noqa
  File "/home/circleci/.cache/torch/hub/pytorch_fairseq_master/fairseq/__init__.py", line 17, in <module>
    import fairseq.criterions  # noqa
  File "/home/circleci/.cache/torch/hub/pytorch_fairseq_master/fairseq/criterions/__init__.py", line 26, in <module>
    importlib.import_module('fairseq.criterions.' + module)
  File "/home/circleci/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/circleci/.cache/torch/hub/pytorch_fairseq_master/fairseq/criterions/adaptive_loss.py", line 12, in <module>
    from fairseq.dataclass.data_class import DDP_BACKEND_CHOICES
  File "/home/circleci/.cache/torch/hub/pytorch_fairseq_master/fairseq/dataclass/data_class.py", line 18, in <module>
    from hydra.core.config_store import ConfigStore
ModuleNotFoundError: No module named 'hydra'

Exited with code exit status 1
```

Which I guess that has something to do with the installation of `hydra-core` which does not appear to be in:

https://github.com/pytorch/hub/blob/5eac8f0358f5ce9c4962f816ffa87b3ec22ed6aa/scripts/install.sh#L13-L15

P.S.: Let me know if this is going in the right direction. Thank you!

**Comment by alvarobartt** [comment]
Hydra package can be found at https://github.com/facebookresearch/hydra

**Comment by ailzhang** [comment]
Closing via #157, thanks for the fix!
